name: Fetch, Build & Deploy (AutoDropship Pro)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "17 3 * * *"  # daily 03:17 UTC

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pyyaml

      - name: Fetch feeds
        run: python scripts/fetch_feeds.py

      - name: Build site
        working-directory: ./site
        run: python build.py

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/out
