name: Fetch Build & Deploy (AutoDropship)

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "17 3 * * *"   # daily 03:17 UTC
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip deps
        run: pip install --upgrade pip && pip install pyyaml

      - name: Fetch feeds (generate site/data/products.csv)
        run: python scripts/fetch_feeds.py

      - name: Build site
        working-directory: ./site
        run: python build.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site/out

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1

